<?php

/**
 * @copyright  Copyright &copy; Gianpaolo Scrigna, letsjump, 2016
 * @package    yii2-widgets
 * @subpackage yii2-widget-barcodyii
 * @version    1.0
 */

namespace letsjump\barcodyii;

use Yii;
use yii\base\Widget;
use yii\helpers\Html;

class Barcodyii extends Widget
{
    /**
     * @var array $action Example: ['barcode/search']
     */
    public $action;
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
    }
    
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        BarcodyiiAsset::register($this->getView());
        $html = Html::beginForm(
            $this->action,
            'get'
        );

        $html .= Html::textInput('code', null, ['class'=>'barcode_input', 'id'=>'barcode_input', 'style'=>'position:absolute; left: -9999px']);


        $html .= Html::endForm();
        
        return 123493487592308453476123894761234;

    }
    
}